config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { registrations: "users/registrations" }

  root to: "static_pages#home"

  resources :feed_categories
  resources :feed_sources
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
    @vueless = false
    @page_header = "RSS Reader"
  end
end

app/views/static_pages/home.html.haml
.h-screen.pb-14.bg-right.bg-cover{:style => ""}
  .w-full.container.mx-auto.p-6
    .w-full.flex.items-center.justify-between
      %a.flex.items-center.text-indigo-400.no-underline.hover:no-underline.font-bold.text-2xl.lg:text-4xl{:href => "#"}
        APP
      %a.flex.items-center.text-indigo-400.no-underline.hover:no-underline.font-bold.text-2xl.lg:text-4xl{href: "/users/sign_up"}
        %h1
          Sign Up
      = link_to destroy_user_session_path, method: :delete, class: 'item' do
        Sign Out

      .flex.justify-end.content-center{:class => "w-1/2"}
        %a.inline-block.text-blue-300.no-underline.hover:text-indigo-800.hover:text-underline.text-center.h-10.p-2.md:h-auto.md:p-4{"data-tippy-content" => "@twitter_handle", :href => "https://twitter.com/intent/tweet?url=#"}
        %a.inline-block.text-blue-300.no-underline.hover:text-indigo-800.hover:text-underline.text-center.h-10.p-2.md:h-auto.md:p-4{"data-tippy-content" => "#facebook_id", :href => "https://www.facebook.com/sharer/sharer.php?u=#"}
  / Main
  .container.pt-24.md:pt-48.px-6.mx-auto.flex.flex-wrap.flex-col.md:flex-row.items-center
    .flex.flex-col.w-full.justify-center.lg:items-start.overflow-y-hidden{:class => "xl:w-2/5"}
      %h1.my-4.text-3xl.md:text-5xl.text-purple-800.font-bold.leading-tight.text-center.md:text-left.slide-in-bottom-h1
        = @page_header
      .div#hello
        %h2.my-4.text-1xl.md:text-5xl.text-pink-300.font-bold.leading-tight.text-center.md:text-left.slide-in-bottom-h1
          {{ message }}
        %app

      %p.leading-normal.text-purple-100.md:text-2xl.mb-8.text-center.md:text-left.slide-in-bottom-subtitle
        A Hobby App built with Rails 6.0 and TailwindCSS
      %p.text-blue-400.font-bold.pb-8.lg:pb-6.text-center.md:text-left.fade-in
        This is some blue text

      = link_to "Feed Sources", feed_sources_path, {class: "flex-shrink-0 bg-purple-500 hover:bg-purple-700 border-purple-500 hover:border-purple-700 text-2xl border-4 text-white py-4 px-8 rounded"}
      .flex.w-full.justify-center.md:justify-start.pb-24.lg:pb-0.fade-in
        %img.h-12.pr-4.bounce-top-icons{:src => ""}/
        %img.h-12.bounce-top-icons{:src => ""}/
    / Right Col
    .w-full.py-6.overflow-y-hidden{:class => "xl:w-3/5"}
      %img.mx-auto.lg:mr-0.slide-in-bottom{:class => "w-5/6", :src => ""}/
    / Footer
    .w-full.pt-16.pb-6.text-sm.text-center.md:text-left.fade-in
      %a.text-gray-500.no-underline.hover:no-underline{:href => "#"} © App 2019