config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { registrations: "users/registrations" }

  root to: "static_pages#home"

  resources :feed_categories
  resources :feed_sources
end

app/models/feed_source.rb
class FeedSource < ApplicationRecord
  validates :url, uniqueness: true
  validate :feed_source_validation

  private

  def feed_source_validation
    parser = RssParser.new

    parser.parse(self)
  end
end

app/controllers/feed_sources_controller.rb
# frozen_string_literal: true

class FeedSourcesController < ApplicationController
  include CrudHelper
  include FeedSourceHelper

  def index
    load_collection
    load_new_model
  end

  def new
    load_new_model
  end

  def edit
    load_model
  end

  def show
    load_model
  end

  def create
    @model = FeedSource.new(resource_params)

    @model.save ? successful_create : unsuccessful_create
  end

  def update
    load_model

    @model.assign_attributes(resource_params)

    @model.save ? successful_update : unsuccessful_update
  end

  def destroy
    load_model

    @model.destroy ? successful_destroy : unsuccessful_destroy
  end

  private

  def resource_params
    params.require(:feed_source).permit(:url)
  end

  def load_model
    @model = FeedSource.find(params[:id])
  end

  def load_collection
    @collection = FeedSource.all
  end

  def load_new_model
    @model = FeedSource.new
  end

  def successful_create
    flash[:success] = create_success_msg

    redirect_to feed_sources_url
  end

  def unsuccessful_create
    respond_to do |format|
      format.js { render_html_form(error: true) }
      format.json { render_json_errors }
      format.html { create_error }
    end
  end

  def successful_update
    respond_to do |format|
      format.js { render_html_form }
      format.json { render_json_success }
      format.html { update_success }
    end
  end

  def update_success
    flash.now[:success] = update_success_msg

    render :edit
  end

  def unsuccessful_update
    respond_to do |format|
      format.js { render_html_form(error: true) }
      format.json { render_json_errors }
      format.html { update_error }
    end
  end

  def successful_destroy
    flash[:success] = destroy_success_msg

    redirect_to feed_sources_url
  end

  def unsuccessful_destroy
    respond_to do |format|
      format.js { render_html_form(error: true) }
      format.html { destroy_error }
    end
  end

  def create_error
    flash.now[:error] = create_error_msg

    render_index
  end

  def destroy_error
    flash.now[:error] = destroy_error_msg

    render_index
  end

  def render_index
    load_collection

    render :index
  end

  def update_error
    flash.now[:error] = update_error_msg

    render :edit
  end
end

app/helpers/feed_source_helper.rb
module FeedSourceHelper
  include ApplicationHelper

  def field_wrapper
    "flex items-center border-b-2 border-pink-200 focus-within:border-purple-500 py-2"
  end

  def txt_field
    "appearance-none bg-transparent border-none w-full text-purple-100 mr-3 py-1 px-4 text-3xl leading-tight focus:outline-none"
  end

  def submit_btn
    "flex-shrink-0 bg-purple-500 hover:bg-purple-700 border-purple-500 hover:border-purple-700 text-lg border-4 text-purple-100 py-2 px-4 rounded"
  end
end

app/views/feed_sources/_feed_source.html.haml
.w-full.pt-3.px-3.md:pr-2{class: "md:w-1/2 xl:w-1/3"}
  .bg-gray-800.rounded.shadow.p-8
    .flex.flex-row.items-center
      .flex-shrink.pl-2.pr-4
        %i.fa.fa-wallet.fa-2x.fa-fw.fa-inverse
          .flex-1.text-right
            %h5.text-purple-600
              = feed_source.url
            = link_to 'Show', feed_source_path(feed_source)
            = link_to 'Edit', edit_feed_source_path(feed_source)
            = form_with(form_options(model: feed_source, class: "", method: :delete)) do |f|
              = f.button "Delete", class: "flex-shrink-0 bg-purple-500 hover:bg-purple-700 border-purple-500 hover:border-purple-700 text-sm border-4 text-purple-100 py-2 px-4 rounded", target: "form.spinnerBtn"

app/views/feed_sources/_form.html.haml
= form_with form_options(model: model,
                         format: auto_submit_format,
                         class: "w-full max-w-2xl") do |f|

  = field_wrapper_for(f.object, :url) do
    = f.text_field :url,
                   class: txt_field,
                   placeholder: "URL",
                   data: { action: "input->form#autoSubmit" }

    = f.button class: submit_btn, data: { target: "form.spinnerBtn" }

app/views/feed_sources/edit.html.haml
.flex.justify-center.my-16
  = render 'feed_sources/form', model: @model

app/views/feed_sources/index.html.haml
.flex.justify-center.my-16
  = render "feed_sources/form", model: @model
.flex.flex-wrap.mb-2
  = render @collection

app/views/feed_sources/new.html.haml
.flex.justify-center.my-16
  = render "feed_sources/form", model: @model

app/views/feed_sources/show.html.haml
= render @model